{1,
{2,
{"",1,0,"",""},
{0,
{"ru",0,0,"","Процедура ОбработкаПолученияНавигационнойСсылки(Элемент, Ключ, Представление, НавигационнаяСсылка, СтандартнаяОбработка)
    <?>
КонецПроцедуры"}
},
{0,
{"en",0,0,"","Procedure URLGetProcessing(ContainsALinkToAPlannerItemToBeEditedOrCopiedOr{ссылка:Объекты;281;Неопределено}WhenAPlannerAreaIs, Key, Presentation, URL, StandardProcessing)
    <?>
EndProcedure"}
}
}
}