{1,
{2,
{"",1,0,"",""},
{0,
{"ru",0,0,"","Процедура ОбработкаПолученияСпискаНавигационныхСсылок(Элемент, СписокНавигационыхСсылок, КлючПоУмолчанию)
    <?>
КонецПроцедуры"}
},
{0,
{"en",0,0,"","Procedure URLListGetProcessing(ContainsALinkToAPlannerItemToBeEditedOrCopiedOr{ссылка:Объекты;281;Неопределено}WhenAPlannerAreaIs, IfTheFormHasThe{ссылка:Атрибуты;9484;АвтоНавигационнаяСсылка}PropertySetTo{ссылка:Атрибуты;4213;Ложь},A, InThisParameter,PutTheKeyValueFromTheURLListThatMatchesTheURLToBeUsedByDefault.)
    <?>
EndProcedure"}
}
}
}