{1,
{2,
{"",1,0,"",""},
{0,
{"ru",0,0,"","Процедура ОбработкаПолученияФормыВыбораПользователейСистемыВзаимодействия(НазначениеВыбора, Форма, Обсуждение, Параметры, ВыбраннаяФорма, СтандартнаяОбработка)
    <?>
КонецПроцедуры"}
},
{0,
{"en",0,0,"","Procedure CollaborationSystemUsersChoiceFormGetProcessing(ChoicePurpose, Form, Conversation, Parameters, SelectedForm, StandardProcessing)
    <?>
EndProcedure"}
}
}
}